### ISSUE TITLE
AttributeError -- terminal

### ISSUE THREAD

**Issue by JacobsThierry** [laowantong/mocodo#54]
Depuis le terminal, lorsque réarrange avec l'option --arrange=lp, une erreur python est levée

```
mocodo --arrange=lp --engine=cplex --input sandbox.mcd

Traceback (most recent call last):
  File "/home/thierry/.local/bin/mocodo", line 8, in <module>
    sys.exit(main())
  File "/home/thierry/.local/lib/python3.8/site-packages/mocodo/__main__.py", line 58, in main
    result = arrange(**params)
  File "/home/thierry/.local/lib/python3.8/site-packages/mocodo/arrange_lp.py", line 140, in arrange
    dump_lp(path, **params)
  File "/home/thierry/.local/lib/python3.8/site-packages/mocodo/arrange_lp.py", line 51, in dump_lp
    push("%s = 1" % summation("x_{v}_{p[0]}_{p[1]}".format(v=v, p=p) for p in P))
  File "/home/thierry/.local/lib/python3.8/site-packages/mocodo/arrange_lp.py", line 14, in push
    result.append("c%s: %s" % (counter.next(), constraint))
AttributeError: 'itertools.count' object has no attribute 'next'
```

L'erreur arrive peu importe le solveur utilisé, le fichier source contient le code qu'il y a par défaut sur mocodo web

Mon mocodo est en version 2.3.8

**Comment by laowantong** [comment]
Apparemment un vieux reste de Python 2 dans une partie obscure du programme. Ça devrait être corrigé, même si j'ai toujours peur de mettre à jour ce vieux code et de tout casser ;)

```
pip install --upgrade mocodo
```

Ceci dit, d'après la doc:

> Actuellement, le temps de résolution par solveur générique est souvent rédhibitoire. L'option n'a été introduite qu'à des fins de recherche, et ne présente pas d'intérêt pratique pour l'utilisateur final.
