### ISSUE TITLE
CplexSolverError -- terminal

### ISSUE THREAD

**Issue by JacobsThierry** [laowantong/mocodo#55]
Depuis le terminal, lorsque réarrange avec l'option --arrange=lp et le moteur cplex, une erreur python est levée : 
```
mocodo --arrange=lp --engine=cplex --input sandbox.mcd

Traceback (most recent call last):
  File "/home/thierry/.local/bin/mocodo", line 8, in <module>
    sys.exit(main())
  File "/home/thierry/.local/lib/python3.8/site-packages/mocodo/__main__.py", line 58, in main
    result = arrange(**params)
  File "/home/thierry/.local/lib/python3.8/site-packages/mocodo/arrange_lp.py", line 143, in arrange
    solution = solve_with_cplex(path)
  File "/home/thierry/.local/lib/python3.8/site-packages/mocodo/arrange_lp.py", line 111, in solve_with_cplex
    problem.set_results_stream("%s_cplex.log" % path)
  File "/usr/local/lib/python3.8/dist-packages/cplex/__init__.py", line 1539, in set_results_stream
    return self._env.set_results_stream(results_file, fn)
  File "/usr/local/lib/python3.8/dist-packages/cplex/_internal/__init__.py", line 273, in set_results_stream
    return self._set_stream(which=self.RESULTS_CHNL_IDX,
  File "/usr/local/lib/python3.8/dist-packages/cplex/_internal/__init__.py", line 252, in _set_stream
    self._streams[which] = _ostream.OutputStream(
  File "/usr/local/lib/python3.8/dist-packages/cplex/_internal/_ostream.py", line 66, in __init__
    raise TypeError("outputfile must have a write method")
TypeError: outputfile must have a write method
Exception ignored in: <function Cplex.__del__ at 0x7f1f1134d430>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/cplex/__init__.py", line 927, in __del__
    self.end()
  File "/usr/local/lib/python3.8/dist-packages/cplex/__init__.py", line 923, in end
    self._env._end()
  File "/usr/local/lib/python3.8/dist-packages/cplex/_internal/__init__.py", line 153, in _end
    self._delete_stream(chnl_idx)
  File "/usr/local/lib/python3.8/dist-packages/cplex/_internal/__init__.py", line 246, in _delete_stream
    _procedural.delfuncdest(self._e, channel,
  File "/usr/local/lib/python3.8/dist-packages/cplex/_internal/_procedural.py", line 306, in delfuncdest
    check_status(env, status)
  File "/usr/local/lib/python3.8/dist-packages/cplex/_internal/_procedural.py", line 249, in __call__
    raise CplexSolverError(error_string, env, status)
cplex.exceptions.errors.CplexSolverError: CPLEX Error  1053: No function pointer found for message routine.

```

Le fichier mit en paramètre contient le code sur mocodo web, mon mocodo est en version 2.3.9, mon python en 3.8.5, et cplex est en 20.10

**Comment by laowantong** [comment]
La version 3.0 ne prend plus en charge la résolution par programmation linéaire.
