### ISSUE TITLE
mocodo ne démarre pas

### ISSUE THREAD

**Issue by GoogleCodeExporter** [laowantong/mocodo#8]
```
Bonjour, 
Je me permet d'écrire en français :)

Je viens de télécharger modoco 1.6 sous Linux (Ubuntu 12.4 64b)

$ uname -a
Linux Julien-HP 3.2.0-35-generic #55-Ubuntu SMP Wed Dec 5 17:42:16 UTC 2012 
x86_64 x86_64 x86_64 GNU/Linux


[julien@Julien-HP mocodo]$ python mocodo.py 
Traceback (most recent call last):
  File "mocodo.py", line 143, in <module>
    sys.exit(main())
  File "mocodo.py", line 110, in main
    params["dirRootExt"] = os.path.join(initialDir,params["input"])
  File "/usr/lib/python2.7/posixpath.py", line 71, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: 
ordinal not in range(128)


[julien@Julien-HP mocodo]$ python --version
Python 2.7.3

N'hésitez pas à me contacter si vous avez besoin de plus d'infos :)

Julien
```

Original issue reported on code.google.com by `Julien.N...@gmail.com` on 2 Jan 2013 at 10:39

**Comment by laowantong** [comment]
Désolé, je n'ai pris connaissance des bogues signalées sur Google Code qu'aujourd'hui en les retrouvant sur GitHub où je viens de faire migrer le projet. Je n'avais pas connaissance de ce problème d'encodage. J'ai complètement réécrit cette partie du code pour la version 2, donc par défaut je suppose qu'il est réglé. N'hésitez pas à me relancer pour rouvrir l'issue le cas échéant.
